"
Watcher for the inputs to #evalObject: in a Lisp interpreter

"
Class {
	#name : #LKMonitor,
	#superclass : #Object,
	#category : #LispKit
}

{ #category : #'as yet unclassified' }
LKMonitor >> goTopLevel [
]

{ #category : #'as yet unclassified' }
LKMonitor >> subLisp: aForm [
]

{ #category : #'as yet unclassified' }
LKMonitor >> subLisp: aForm from: aLisp [
]

{ #category : #'as yet unclassified' }
LKMonitor >> symbolsValuesAdded: anAssociation in: aLisp [
]

{ #category : #'as yet unclassified' }
LKMonitor >> trace: anObject in: aLisp [

	^ anObject
]

{ #category : #'as yet unclassified' }
LKMonitor >> traceResult: anObject for: bObject in: aLisp [
]
