name: Interpreters Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: "lts/Hydrogen"
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4"

    - name: Run Python Interpreter Tests
      run: |
        python3 rosetta-test-py/interpreter-tests.py
    - name: Run JavaScript Interpreter Tests
      run: |
        node rosetta-test-js/interpreter-tests.js
    - name: Run Ruby Interpreter Tests
      run: |
        ruby rosetta-test-rb/interpreter-tests.rb

    