name: JavaScript Suites

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: "lts/Hydrogen"
        cache: 'npm'
    - name: Run JSON RFC Tests
      run: |
        node rosetta-test-js/json-rfc.js
    - name: Run URL Tests
      run: |
        node rosetta-test-js/url-parsing.js