name: Python Suites

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run SMTP Tests
      run: |
        python3 rosetta-test-py/smtp.py
    - name: Run Sendmail Tests for RedMail
      run: |
        pip install -r rosetta-test-py/sendmail-redmail.requirements.txt
        python3 rosetta-test-py/sendmail-redmail.py
    - name: Run Sendmail Tests for Python Emails
      run: |
        pip install -r rosetta-test-py/sendmail-python-emails.requirements.txt
        python3 rosetta-test-py/sendmail-python-emails.py
    - name: Run JSON RFC Tests
      run: |
        python3 rosetta-test-py/json-rfc.py
